//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class TypeItem
{
	public int ID = -1;
	public string TypeName = "";
	public List<string> TypeList = new List<string>();

	public TypeItem ()
	{
	}
}


